version: '3.1'

services:
  db:
    image: mysql:8.0
    restart: always
    ports:
      - 3307:3306
    environment:
      MYSQL_DATABASE: calender
      MYSQL_USER: calender
      MYSQL_PASSWORD: calender
      MYSQL_RANDOM_ROOT_PASSWORD: calender

